package com.startechnology.start_core.machine.hellforge;

import com.gregtechceu.gtceu.GTCEu;
import com.gregtechceu.gtceu.api.GTCEuAPI;
import com.gregtechceu.gtceu.api.data.RotationState;
import com.gregtechceu.gtceu.api.data.chemical.ChemicalHelper;
import com.gregtechceu.gtceu.api.data.tag.TagPrefix;
import com.gregtechceu.gtceu.api.machine.MultiblockMachineDefinition;
import com.gregtechceu.gtceu.api.machine.multiblock.PartAbility;
import com.gregtechceu.gtceu.api.pattern.FactoryBlockPattern;
import com.gregtechceu.gtceu.api.pattern.Predicates;
import com.gregtechceu.gtceu.common.data.GCYMBlocks;
import com.gregtechceu.gtceu.common.data.GTBlocks;
import com.gregtechceu.gtceu.common.data.GTRecipeModifiers;
import com.gregtechceu.gtceu.common.data.GTRecipeTypes;
import com.startechnology.start_core.machine.StarTMachineUtils;
import com.startechnology.start_core.machine.StarTPartAbility;
import com.startechnology.start_core.machine.bacteria.BacterialRunicMutator;
import com.startechnology.start_core.recipe.StarTRecipeModifiers;
import com.startechnology.start_core.recipe.StarTRecipeTypes;

import static com.startechnology.start_core.StarTCore.START_REGISTRATE;

import dev.latvian.mods.kubejs.KubeJS;
import net.minecraft.network.chat.Component;
import net.minecraft.resources.ResourceLocation;
import net.minecraftforge.registries.ForgeRegistries;

import java.util.List;

public class StarTHellForgeMachines {

    public static final MultiblockMachineDefinition HELL_FORGE = START_REGISTRATE
        .multiblock("hellforge", holder -> (new StarTHellForgeMachine(holder, 0, 5, 125)))
        .appearanceBlock(() -> StarTMachineUtils.getKjsBlock(("extreme_temperature_smelting_casing")))
        .langValue("Hell Forge [HF]")
        .tooltips(
            Component.translatable("block.start_core.hellforge_multiblock_line"),
            Component.translatable("block.start_core.hellforge_description"),
            Component.translatable("block.start_core.breaker_line")
        )
        .paginatedTooltips(
            List.of(
                List.of(
                    Component.translatable("block.start_core.hellforge_d0"),
                    Component.translatable("block.start_core.hellforge_d1"),
                    Component.empty(),
                    Component.translatable("block.start_core.hellforge_d2"),
                    Component.empty(),
                    Component.translatable("block.start_core.hellforge_d9"),
                    Component.empty(),
                    Component.translatable("block.start_core.hellforge_d3")
                ),
                List.of(
                    Component.translatable("block.start_core.hellforge_d5"),
                    Component.translatable("block.start_core.hellforge_d6"),
                    Component.translatable("block.start_core.breaker_line"),
                    Component.translatable("machine.start_core.redstone_interfacing"),
                    Component.translatable("block.start_core.hellforge_d8")
                )
            )
        )
        .recipeModifiers(GTRecipeModifiers.OC_NON_PERFECT, StarTRecipeModifiers.HELL_FORGE_OC, GTRecipeModifiers.BATCH_MODE)
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeTypes(StarTRecipeTypes.HELL_FORGE_RECIPES)
        .pattern(definition -> FactoryBlockPattern.start()
            .aisle("    B   B    ", "    B   B    ", "    B   B    ", "    B   B    ", "    BBBBB    ", "    CCCCC    ", "             ", "             ", "             ", "      D      ", "    DDDDD    ", "      D      ", "             ", "             ", "             ", "    CCCCC    ", "    BBBBB    ", "             ", "    BBBBB    ", "             ", "             ", "             ", "             ", "             ", "             ", "             ", "             ", "             ", "      E      ", "      E      ", "      E      ", "             ")
            .aisle(" B  BBBBB  B ", " B  FEEEF  B ", " B  FEGEF  B ", " B  FEEEF  B ", " BBBBBBBBBBB ", " CCCEEEEECCC ", "    EEEEE    ", "     EEE     ", "             ", "             ", "  DD     DD  ", "             ", "             ", "     EEE     ", "    EEEEE    ", " CCCEEEEECCC ", " BBBHHHHHBBB ", "    FFFFF    ", " BBB     BBB ", "             ", "             ", "             ", "             ", "             ", "             ", "             ", "             ", "      E      ", "    E   E    ", "    E   E    ", "        E    ", "      E      ")
            .aisle("  BBFBBBFBB  ", "  FF     FF  ", "  FF     FF  ", "  FF     FF  ", " BBBFFFFFBBB ", " CHHHHHHHHHC ", "  HHHHHHHHH  ", "    HHEHH    ", "     E E     ", "             ", " D         D ", "             ", "     E E     ", "    HHEHH    ", "  HHHHHHHHH  ", " CHHHHHHHHHC ", " BHHIIIIIHHB ", "  FF     FF  ", " B         B ", "             ", "             ", "             ", "    DDDDD    ", "             ", "             ", "             ", "      E E    ", "    E E E    ", "             ", "             ", "    E        ", "        E    ")
            .aisle("  BFFBBBFFB  ", "  F  III  F  ", "  F  III  F  ", "  F  III  F  ", " BBFFIIIFFBB ", " CHHHIIIHHHC ", "  HHHIIIHHH  ", "   HHIIIHH   ", "   HHJJJHH   ", "   HE J EH   ", " D  E   E  D ", "   HE J EH   ", "   HHJJJHH   ", "   HHIIIHH   ", "  HHHIIIHHH  ", " CHHHIIIHHHC ", " BHIIIIIIIHB ", "  F  JJJ  F  ", " B   IKI   B ", "     JJJ     ", "             ", "             ", "   D     D   ", "             ", "             ", "     E E     ", "    EEHEH    ", "    E        ", "         E   ", "         E   ", "             ", "             ")
            .aisle("BBFFBBBBBFFBB", "BF  GIFIG  FB", "BF  GJ JG  FB", "BF  GJ JG  FB", "BBFFG   GFFBB", "CEHHG   GHHEC", " EHHG   GHHE ", "  HHG   GHH  ", "   HGBCBGH   ", "   EGBJBGE   ", "D  EGBLBGE  D", "   EGBJBGE   ", "   HGBCBGH   ", "  HHG   GHH  ", " EHHG   GHHE ", "CEHHG   GHHEC", "BHIIG   GIIHB", " F  JJ JJ  F ", "B   IJ JI   B", "    JEBEJ    ", "    JEBEJ    ", "     EBE     ", "  D  EBH  D  ", "     EBE     ", "     EBE     ", "    EEEEE    ", "    HEEEEE   ", "         E   ", "             ", "             ", "         E   ", "             ")
            .aisle(" BFBBBBBBBFB ", " E IIIIIII E ", " E IJ   JI E ", " E IJ   JI E ", "BBFI     IFBB", "CEHI     IHEC", " EHI     IHE ", " EHI     IHE ", "  EJB C BJE  ", "    B   B    ", "D   B   B   D", "    B   B    ", "  EJB C BJE  ", " EHI     IHE ", " EHI     IHE ", "CEHI     IHEC", "BHII     IIHB", " F JJ   JJ F ", "B  IJ   JI  B", "   JE   EJ   ", "    E B E    ", "    E   E    ", "  D E   E D  ", "    H   E    ", "    EEEEE    ", "    EBBBEE   ", "        HE   ", "             ", "             ", "             ", "             ", "             ")
            .aisle(" BFBBBBBBBFB ", " E IFIIIFI E ", " G I  G  I G ", " E I  G  I E ", "BBFI  G  IFBB", "CEHI  G  IHEC", " EHI     IHE ", " EEI     IEE ", "   JCCECCJ   ", "D  JJ E JJ  D", "D   L M L   D", "D  JJ E JJ  D", "   JCCECCJ   ", " EEI     IEE ", " EHI     IHE ", "CEHI     IHEC", "BHII     IIHB", " F J     J F ", "B  K     K  B", "   JB   BJ   ", "    B B B    ", "    B B B    ", "  D B   B D  ", "    B   B    ", "    BEEEB    ", "     BBBEE   ", "             ", "             ", "      D      ", "     DDD     ", "     DDD     ", "      D      ")
            .aisle(" BFBBBBBBBFB ", " E IIIIIII E ", " E IJ   JI E ", " E IJ   JI E ", "BBFI     IFBB", "CEHI     IHEC", " EHI     IHE ", " EHI     IHE ", "  EJB C BJE  ", "    B   B    ", "D   B   B   D", "    B   B    ", "  EJB C BJE  ", " EHI     IHE ", " EHI     IHE ", "CEHI     IHEC", "BHII     IIHB", " F JJ   JJ F ", "B  IJ   JI  B", "   JE   EJ   ", "    E   E    ", "    E   E    ", "  D E   E D  ", "    H   H    ", "    EEBEEE   ", "        HEE  ", "         EE  ", "          E  ", "          E  ", "             ", "             ", "             ")
            .aisle("BBFFBBBBBFFBB", "BF  GIFIG  FB", "BF  GJ JG  FB", "BF  GJ JG  FB", "BBFFG   GFFBB", "CEHHG   GHHEC", " EHHG   GHHE ", "  HHG   GHH  ", "   HGBCBGH   ", "   EGBJBGE   ", "D  EGBLBGE  D", "   EGBJBGE   ", "   HGBCBGH   ", "  HHG   GHH  ", " EHHG   GHHE ", "CEHHG   GHHEC", "BHIIG   GIIHB", " F  JJ JJ  F ", "B   IJ JI   B", "    JEBEJ    ", "    JEBEJ    ", "     EBE     ", "  D  HBE  D  ", "     EBE     ", "     EBE     ", "             ", "             ", "             ", "             ", "             ", "             ", "             ")
            .aisle("  BFFBBBFFB  ", "  F  III  F  ", "  F  III  F  ", "  F  III  F  ", " BBFFIIIFFBB ", " CHHHIIIHHHC ", "  HHHIIIHHH  ", "   HHIIIHH   ", "   HHJJJHH   ", "   HE J EH   ", " D  E   E  D ", "   HE J EH   ", "   HHJJJHH   ", "   HHIIIHH   ", "  HHHIIIHHH  ", " CHHHIIIHHHC ", " BHIIIIIIIHB ", "  F  JJJ  F  ", " B   IKI   B ", "     JJJ     ", "             ", "             ", "   D     D   ", "             ", "             ", "             ", "             ", "             ", "             ", "             ", "             ", "             ")
            .aisle("  BBFFFFFBB  ", "  FF     FF  ", "  FF     FF  ", "  FF     FF  ", " BBBFFFFFBBB ", " CHHHHHHHHHC ", "  HHHHHHHHH  ", "    HHEHH    ", "     E E     ", "             ", " D         D ", "             ", "     E E     ", "    HHEHH    ", "  HHHHHHHHH  ", " CHHHHHHHHHC ", " BHHIIIIIHHB ", "  FF     FF  ", " B         B ", "             ", "             ", "             ", "    DDDDD    ", "             ", "             ", "             ", "             ", "             ", "             ", "             ", "             ", "             ")
            .aisle(" B  BBBBB  B ", " B  FEEEF  B ", " B  FE@EF  B ", " B  FEEEF  B ", " BBBBBBBBBBB ", " CCCEEEEECCC ", "    EEEEE    ", "     EEE     ", "             ", "             ", "  DD     DD  ", "             ", "             ", "     EEE     ", "    EEEEE    ", " CCCEEEEECCC ", " BBBHHHHHBBB ", "    FFFFF    ", " BBB     BBB ", "             ", "             ", "             ", "             ", "             ", "             ", "             ", "             ", "             ", "             ", "             ", "             ", "             ")
            .aisle("    B   B    ", "    B   B    ", "    B   B    ", "    B   B    ", "    BBBBB    ", "    CCCCC    ", "             ", "             ", "             ", "      D      ", "    DDDDD    ", "      D      ", "             ", "             ", "             ", "    CCCCC    ", "    BBBBB    ", "             ", "    BBBBB    ", "             ", "             ", "             ", "             ", "             ", "             ", "             ", "             ", "             ", "             ", "             ", "             ", "             ")
            .where(" ", Predicates.any())
            .where("B", Predicates.blocks(StarTMachineUtils.getKjsBlock("noble_mixing_casing")))
            .where("C", Predicates.blocks(ChemicalHelper.getBlock(TagPrefix.frameGt, GTCEuAPI.materialManager.getMaterial("gtceu:astrenalloy_nx"))))
            .where("D", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.of("thermal:signalum_glass", ':'))))
            .where("E", Predicates.blocks(StarTMachineUtils.getKjsBlock("extreme_temperature_smelting_casing"))
                .or(Predicates.abilities(PartAbility.IMPORT_FLUIDS).setMaxGlobalLimited(8).setPreviewCount(0))
                .or(Predicates.abilities(PartAbility.EXPORT_FLUIDS).setMaxGlobalLimited(2).setPreviewCount(0))
                .or(Predicates.abilities(PartAbility.IMPORT_ITEMS).setMaxGlobalLimited(2).setPreviewCount(0))
                .or(Predicates.abilities(PartAbility.EXPORT_ITEMS).setMaxGlobalLimited(2).setPreviewCount(0))
                .or(Predicates.abilities(PartAbility.INPUT_ENERGY).setMaxGlobalLimited(2))
                .or(Predicates.abilities(PartAbility.MAINTENANCE).setExactLimit(1))
                .or(Predicates.abilities(StarTPartAbility.REDSTONE_INTERFACE).setMaxGlobalLimited(4).setPreviewCount(0)))
            .where("F", Predicates.blocks(GCYMBlocks.HEAT_VENT.get()))
            .where("G", Predicates.blocks(StarTMachineUtils.getKjsBlock("enriched_naquadah_pipe_casing")))
            .where("H", Predicates.blocks(StarTMachineUtils.getKjsBlock("reinforced_brimstone_casing")))
            .where("I", Predicates.blocks(StarTMachineUtils.getKjsBlock("enriched_naquadah_machine_casing")))
            .where("J", Predicates.blocks(GCYMBlocks.CASING_ATOMIC.get()))
            .where("K", Predicates.blocks(StarTMachineUtils.getKjsBlock("runic_stabilization_casing")))
            .where("L", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.of("thermal_extra:shellite_glass", ':'))))
            .where("M", Predicates.blocks(StarTMachineUtils.getKjsBlock("heart_of_the_flame")))
            .where("@", Predicates.controller(Predicates.blocks(definition.get())))
            .build()
        )
        .workableCasingModel(KubeJS.id("block/casings/nether_multis/extreme_temperature_smelting_casing"),
            GTCEu.id("block/machines/alloy_smelter"))
        .register();

    public static final MultiblockMachineDefinition BOOSTED_HELL_FORGE = START_REGISTRATE
        .multiblock("fornaxs_infernal_rotary_engine", holder -> (new StarTHellForgeMachine(holder, 925, 3, 75)))
        .appearanceBlock(() -> StarTMachineUtils.getKjsBlock(("absolute_temperature_smelting_casing")))
        .langValue("Fornaxs Infernal Rotary Engine [FIRE]")
        .tooltips(
            Component.translatable("block.start_core.fornaxs_infernal_rotary_engine_line"),
            Component.translatable("block.start_core.fornaxs_infernal_rotary_engine_description"),
            Component.translatable("block.start_core.breaker_line")
        )
        .paginatedTooltips(
            List.of(
                List.of(
                    Component.translatable("block.start_core.fornaxs_infernal_rotary_engine_d0"),
                    Component.translatable("block.start_core.fornaxs_infernal_rotary_engine_d1"),
                    Component.empty(),
                    Component.translatable("block.start_core.fornaxs_infernal_rotary_engine_d2"),
                    Component.empty(),
                    Component.translatable("block.start_core.fornaxs_infernal_rotary_engine_d9"),
                    Component.empty(),
                    Component.translatable("block.start_core.fornaxs_infernal_rotary_engine_d3")
                ),
                List.of(
                    Component.translatable("block.start_core.fornaxs_infernal_rotary_engine_d5"),
                    Component.translatable("block.start_core.fornaxs_infernal_rotary_engine_d6"),
                    Component.translatable("block.start_core.breaker_line"),
                    Component.translatable("machine.start_core.redstone_interfacing"),
                    Component.translatable("block.start_core.hellforge_d8")
                )
            )
        )
        .recipeModifiers(GTRecipeModifiers.OC_NON_PERFECT, StarTRecipeModifiers.HELL_FORGE_OC, StarTRecipeModifiers.THROUGHPUT_BOOSTING, GTRecipeModifiers.BATCH_MODE)
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeTypes(StarTRecipeTypes.HELL_FORGE_RECIPES)
        .pattern(definition -> FactoryBlockPattern.start()
            .aisle("         B B         ", "         B B         ", "         B B         ", "         B B         ", "         B B         ", "         D D         ", "                     ", "                     ", "          E          ", "          E          ", "         EEE         ", "         E E         ", "         EEE         ", "          E          ", "          E          ", "                     ", "                     ", "        D   D        ", "        B   B        ", "        B   B        ", "        B   B        ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ")
            .aisle("       BBBBBBB       ", "       B     B       ", "       B     B       ", "       B     B       ", "       BBBBBBB       ", "       DDDDDDD       ", "                     ", "                     ", "                     ", "                     ", "          E          ", "       EEE EEE       ", "          E          ", "                     ", "                     ", "                     ", "                     ", "       DDDDDDD       ", "       BBBBBBB       ", "                     ", "       BBBBBBB       ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ")
            .aisle("     BBBCCCCCBBB     ", "     B  CFCFC  B     ", "     B  CGCGC  B     ", "     B  CFCFC  B     ", "     BBBCCCCCBBB     ", "     DDDCCCCCDDD     ", "        CCCCC        ", "         CCC         ", "                     ", "                     ", "                     ", "     EE       EE     ", "                     ", "                     ", "                     ", "         CCC         ", "        CCCCC        ", "     DDDCCCCCDDD     ", "     BBBHHHHHBBB     ", "        IIIII        ", "     BBB     BBB     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ")
            .aisle("   BBBCCCCCCCCCBBB   ", "   B  IICCCCCII  B   ", "   B  IICCJCCII  B   ", "   B  IICCCCCII  B   ", "   BBBCCCCCCCCCBBB   ", "   DDDHCCCCCCCHDDD   ", "      HCCCCCCCH      ", "        CCCCC        ", "   E     CCC     E   ", "   E             E   ", "   EE           EE   ", "    E           E    ", "   EE           EE   ", "   E             E   ", "   E     CCC     E   ", "        CCCCC        ", "      HCCCCCCCH      ", "   DDDHCCCCCCCHDDD   ", "   BBBHHHKJKHHHBBB   ", "   B  III   III  B   ", "   BBB         BBB   ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ")
            .aisle("   BCCCCCCCCCCCCCB   ", "    FGCC     CCGF    ", "    KJCC  J  CCJK    ", "    FGCC     CCGF    ", "   BCCCCBBBBBCCCCB   ", "   DHHHCCCCCCCHHHD   ", "    HHHCCCCCCCHHH    ", "      HHCCCCCHH      ", "       HHCCCHH       ", "         H H         ", "   E             E   ", "   E             E   ", "   E             E   ", "         H H         ", "       HHCCCHH       ", "      HHCCCCCHH      ", "    HHHCCCCCCCHHH    ", "   DHHHCCCCCCCHHHD   ", "   BHHHKJFFFJKHHHB   ", "    III       III    ", "   B             B   ", "                     ", "                     ", "          E          ", "        EEEEE        ", "          E          ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ")
            .aisle("  BBCCCCIIIIICCCCBB  ", "  B GCC       CCG B  ", "  B JJC   J   CJJ B  ", "  B GCC       CCG B  ", "  BBCCBBB   BBBCCBB  ", "  DDHHCCC   CCCHHDD  ", "    HHCCCC CCCCHH    ", "     HCCCCCCCCCH     ", "     HCCCCCCCCCH     ", "      CCCBBBCCC      ", "       CC B CC       ", "  E     C   C     E  ", "       CC B CC       ", "      CCCBBBCCC      ", "     HCCCCCCCCCH     ", "     HCCCCCCCCCH     ", "    HHCCCCCCCCCHH    ", "  DDHHCCCCCCCCCHHDD  ", "  BBHKJFFJKJFFJKHBB  ", "    I           I    ", "  BB             BB  ", "                     ", "                     ", "                     ", "      EE     EE      ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ")
            .aisle("  BCCCCIIIIIIICCCCB  ", "   ICC         CCI   ", "   ICCJ   J   JCCI   ", "   ICC         CCI   ", "  BCCBB       BBCCB  ", "  DHHCC       CCHHD  ", "   HHCCC     CCCHH   ", "    HCCCCCCCCCCCH    ", "     CCCCBBBCCCC     ", "     CCCCBBBCCCC     ", "      CCCBBBCCC      ", "  E   CCCBLBCCC   E  ", "      CCCBBBCCC      ", "     CCCCBBBCCCC     ", "     CCCCBBBCCCC     ", "    HCCCCCCCCCCCH    ", "   HHCCCCCCCCCCCHH   ", "  DHHCCCCCCCCCCCHHD  ", "  BHHJFJKCCCKJFJHHB  ", "   II    BBB    II   ", "  B      GMG      B  ", "         BBB         ", "                     ", "                     ", "     E         E     ", "                     ", "                     ", "                     ", "                     ", "                     ", "         C C         ", "         C C         ", "         C C         ", "         C C         ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ")
            .aisle(" BBCCCIIICCCIIICCCBB ", " B IC           CI B ", " B IC  J  J  J  CI B ", " B IC           CI B ", " BBCCB  BBBBB  BCCBB ", " DDCCC         CCCDD ", "   CCCC       CCCC   ", "    HCCCCCCCCCCCH    ", "    HCCBB   BBCCH    ", "     CCG  D  GCC     ", "     CCJ     JCC     ", " E    CF     FC    E ", "     CCJ     JCC     ", "     CCG  D  GCC     ", "    HCCBB   BBCCH    ", "    HCCCCCCCCCCCH    ", "   CCCCCCCCCCCCCCC   ", " DDCCCCCCIIICCCCCCDD ", " BBHKFJCCIIICCJFKHBB ", "   I   BBIIIBB   I   ", " BB    MGCICGM    BB ", "       BBCICBB       ", "         CHC         ", "         CHC         ", "     E   CHC   E     ", "          H          ", "          H          ", "                     ", "                     ", "        CC CC        ", "      CC C C C       ", "      C       C      ", "     C         C     ", "     C         C     ", "     C         C     ", "      C       C      ", "                     ", "                     ", "                     ", "                     ")
            .aisle(" BCCCIIICCCCCIIICCCB ", "  CC     CCC     CC  ", "  CC    JCJCJ    CC  ", "  CC     CCC     CC  ", " BCCBB BBCCCBB BBCCB ", " DCCCC   CFC   CCCCD ", "  CCCC  CCJCC  CCCC  ", "   CCCCCGG GGCCCCC   ", "    HCCB     BCCH    ", "     CC   D   CC     ", "     CC       CC     ", " E   CC       CC   E ", "     CC       CC     ", "     CC   D   CC     ", "    HCCB     BCCH    ", "   CCCCCGG GGCCCCC   ", "  CCCCCCCFJFCCCCCCC  ", "DDCCCCCCC   CCCCCCCDD", "BBHHJFKCC   CCKFJHHBB", "B II   BC   CB   II B", "BB     GCC CCG     BB", "       BCC CCB       ", "        CCCCC        ", "        CCCCC        ", "    E    CCC    E    ", "         CCC         ", "         CCC         ", "         CCC         ", "       CCC CCC       ", "      CCCC CCCC      ", "    CCCC     CCCC    ", "    C           C    ", "   C             C   ", "   C             C   ", "   C             C   ", "   C             C   ", "    C           C    ", "                     ", "                     ", "                     ")
            .aisle("BBCCCIICCCICCCIICCCBB", "B FC    CGFGC    CF B", "B GC    CJ JC    CG B", "B FC    CGFGC    CF B", "BBCCB  BCCJCCB  BCCBB", "DDCCC   CJ JC   CCCDD", "  CCCC  CF FC  CCCC  ", "  CCCCCCG   GCCCCCC  ", "   CCCB       BCCC   ", "    HBB   D   BBH    ", "E     B       B     E", "EE    B       B    EE", "E     B       B     E", "    HBB   D   BBH    ", "   CCCB       BCCC   ", "  CCCCCCG   GCCCCCC  ", "  CCCCCCF   FCCCCCC  ", " DCCCCCI     ICCCCCD ", " BHKFJCI     ICJFKHB ", "  I   BI     IB   I  ", " B    GI     IG    B ", "      BCC   CCB      ", "       HC   CH       ", "       HC   CH       ", "    E  HHC CHH  E    ", "        HC CH        ", "        HCICH        ", "       HHC CHH       ", "       CCC CCC       ", "      CHH   HHC      ", "     CH       HC     ", "                     ", "                     ", "                     ", "          E          ", "         EEE         ", "         EEE         ", "          E          ", "                     ", "                     ")
            .aisle(" BCCCIICCIIICCIICCCB ", "  CC    CF FC    CC  ", "  CJJJJJJ   JJJJJJC  ", "  CC    CF FC    CC  ", " BCCB  BCJ JCB  BCCB ", " DCCC   F   F   CCCD ", "  CCC   J   J   CCC  ", "  CCCCCC     CCCCCC  ", "E  CCCB       BCCC  E", "E    BBDDDCDDDBB    E", "EE   BB   C   BB   EE", "      L   N   L      ", "EE   BB   C   BB   EE", "E    BBDDDCDDDBB    E", "E  CCCB       BCCC  E", "  CCCCCC     CCCCCC  ", "  CCCCCCJ   JCCCCCC  ", " DCCCCCI     ICCCCCD ", " BHJFKCI     ICKFJHB ", "  I   BHHHHHHHB   I  ", " B    MI  H  IM    B ", "      BI  H  IB      ", "       CC H CC       ", "    E  CC   CC  E    ", "    E  CC   CC  E    ", "    E  CCC CCC  E    ", "      CCCCICCCC      ", "      CCCC CCCC      ", "     CCHHC CHHCC     ", "     CCHH   HHCC     ", "    CCH       HCC    ", "    C           C    ", "   C      E      C   ", "   C     EEE     C   ", "   C     EEE     C   ", "    C    EEE    C    ", "         EEE         ", "         EEE         ", "         EEE         ", "          E          ")
            .aisle("BBCCCIICCCICCCIICCCBB", "B FC    CGFGC    CF B", "B GC    CJ JC    CG B", "B FC    CGFGC    CF B", "BBCCB  BCCJCCB  BCCBB", "DDCCC   CJ JC   CCCDD", "  CCCC  CF FC  CCCC  ", "  CCCCCCG   GCCCCCC  ", "   CCCB       BCCC   ", "    HBB   D   BBH    ", "E     B       B     E", "EE    B       B    EE", "E     B       B     E", "    HBB   D   BBH    ", "   CCCB       BCCC   ", "  CCCCCCG   GCCCCCC  ", "  CCCCCCF   FCCCCCC  ", " DCCCCCI     ICCCCCD ", " BHKFJCI     ICJFKHB ", "  I   BI     IB   I  ", " B    GI     IG    B ", "      BCC   CCB      ", "       HC   CH       ", "       HC   CH       ", "    E  HHC CHH  E    ", "        HC CH        ", "        HCICH        ", "       HHC CHH       ", "       CHC CHC       ", "      CH     HC      ", "     CC       CC     ", "                     ", "                     ", "                     ", "          E          ", "         EEE         ", "         EEE         ", "          E          ", "                     ", "                     ")
            .aisle(" BCCCIIICCCCCIIICCCB ", "  CC     CCC     CC  ", "  CC    JCJCJ    CC  ", "  CC     CCC     CC  ", " BCCBB BBCCCBB BBCCB ", " DCCCC   CFC   CCCCD ", "  CCCC  CCJCC  CCCC  ", "   CCCCCGG GGCCCCC   ", "    HCCB     BCCH    ", "     CC   D   CC     ", "     CC       CC     ", " E   CC       CC   E ", "     CC       CC     ", "     CC   D   CC     ", "    HCCB     BCCH    ", "   CCCCCGG GGCCCCC   ", "  CCCCCCCFJFCCCCCCC  ", "DDCCCCCCC   CCCCCCCDD", "BBHHJFKCC   CCKFJHHBB", "B II   BC   CB   II B", "BB     GCC CCG     BB", "       BCC CCB       ", "        CCCCC        ", "        CCCCC        ", "    E    CCC    E    ", "         CCC         ", "         CCC         ", "         CCC         ", "       CCC CCC       ", "      CC     CC      ", "     CC       CC     ", "     C         C     ", "    C           C    ", "    C           C    ", "     C         C     ", "                     ", "                     ", "                     ", "                     ", "                     ")
            .aisle(" BBCCCIIICCCIIICCCBB ", " B IC           CI B ", " B IC  J  J  J  CI B ", " B IC           CI B ", " BBCCB  BBBBB  BCCBB ", " DDCCC         CCCDD ", "   CCCC       CCCC   ", "    HCCCCCCCCCCCH    ", "    HCCBB   BBCCH    ", "     CCG  D  GCC     ", "     CCJ     JCC     ", " E    CF     FC    E ", "     CCJ     JCC     ", "     CCG  D  GCC     ", "    HCCBB   BBCCH    ", "    HCCCCCCCCCCCH    ", "   CCCCCCCCCCCCCCC   ", " DDCCCCCCIIICCCCCCDD ", " BBHKFJCCIIICCJFKHBB ", "   I   BBIIIBB   I   ", " BB    MGCICGM    BB ", "       BBCICBB       ", "         CHC         ", "         CHC         ", "     E   CHC   E     ", "          H          ", "          H          ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ")
            .aisle("  BCCCCIIIIIIICCCCB  ", "   ICC         CCI   ", "   ICCJ   J   JCCI   ", "   ICC         CCI   ", "  BCCBB       BBCCB  ", "  DHHCC       CCHHD  ", "   HHCCC     CCCHH   ", "    HCCCCCCCCCCCH    ", "     CCCCBBBCCCC     ", "     CCCCBBBCCCC     ", "      CCCBBBCCC      ", "  E   CCCBLBCCC   E  ", "      CCCBBBCCC      ", "     CCCCBBBCCCC     ", "     CCCCBBBCCCC     ", "    HCCCCCCCCCCCH    ", "   HHCCCCCCCCCCCHH   ", "  DHHCCCCCCCCCCCHHD  ", "  BHHJFJKCCCKJFJHHB  ", "   II    BBB    II   ", "  B      GMG      B  ", "         BBB         ", "                     ", "                     ", "     E         E     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ")
            .aisle("  BBCCCCIIIIICCCCBB  ", "  B GCC       CCG B  ", "  B JJC   J   CJJ B  ", "  B GCC       CCG B  ", "  BBCCBBB   BBBCCBB  ", "  DDHHCCC   CCCHHDD  ", "    HHCCCC CCCCHH    ", "     HCCCCCCCCCH     ", "     HCCCCCCCCCH     ", "      CCCBBBCCC      ", "       CC B CC       ", "  E     C   C     E  ", "       CC B CC       ", "      CCCBBBCCC      ", "     HCCCCCCCCCH     ", "     HCCCCCCCCCH     ", "    HHCCCCCCCCCHH    ", "  DDHHCCCCCCCCCHHDD  ", "  BBHKJFFJKJFFJKHBB  ", "    I           I    ", "  BB             BB  ", "                     ", "                     ", "                     ", "      EE     EE      ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ")
            .aisle("   BCCCCCCCCCCCCCB   ", "    FGCC     CCGF    ", "    KJCC  J  CCJK    ", "    FGCC     CCGF    ", "   BCCCCBBBBBCCCCB   ", "   DHHHCCCCCCCHHHD   ", "    HHHCCCCCCCHHH    ", "      HHCCCCCHH      ", "       HHCCCHH       ", "         H H         ", "   E             E   ", "   E             E   ", "   E             E   ", "         H H         ", "       HHCCCHH       ", "      HHCCCCCHH      ", "    HHHCCCCCCCHHH    ", "   DHHHCCCCCCCHHHD   ", "   BHHHKJFFFJKHHHB   ", "    III       III    ", "   B             B   ", "                     ", "                     ", "          E          ", "        EEEEE        ", "          E          ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ")
            .aisle("   BBBCCCCCCCCCBBB   ", "   B  IICCCCCII  B   ", "   B  IICCJCCII  B   ", "   B  IICCCCCII  B   ", "   BBBCCCCCCCCCBBB   ", "   DDDHCCCCCCCHDDD   ", "      HCCCCCCCH      ", "        CCCCC        ", "   E     CCC     E   ", "   E             E   ", "   EE           EE   ", "    E           E    ", "   EE           EE   ", "   E             E   ", "   E     CCC     E   ", "        CCCCC        ", "      HCCCCCCCH      ", "   DDDHCCCCCCCHDDD   ", "   BBBHHHKJKHHHBBB   ", "   B  III   III  B   ", "   BBB         BBB   ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ")
            .aisle("     BBBCCCCCBBB     ", "     B  CFCFC  B     ", "     B  CG@GC  B     ", "     B  CFCFC  B     ", "     BBBCCCCCBBB     ", "     DDDCCCCCDDD     ", "        CCCCC        ", "         CCC         ", "                     ", "                     ", "                     ", "     EE       EE     ", "                     ", "                     ", "                     ", "         CCC         ", "        CCCCC        ", "     DDDCCCCCDDD     ", "     BBBHHHHHBBB     ", "        IIIII        ", "     BBB     BBB     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ")
            .aisle("       BBBBBBB       ", "       B     B       ", "       B     B       ", "       B     B       ", "       BBBBBBB       ", "       DDDDDDD       ", "                     ", "                     ", "                     ", "                     ", "          E          ", "       EEE EEE       ", "          E          ", "                     ", "                     ", "                     ", "                     ", "       DDDDDDD       ", "       BBBBBBB       ", "                     ", "       BBBBBBB       ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ")
            .aisle("         B B         ", "         B B         ", "         B B         ", "         B B         ", "         B B         ", "         D D         ", "                     ", "                     ", "          E          ", "          E          ", "         EEE         ", "         E E         ", "         EEE         ", "          E          ", "          E          ", "                     ", "                     ", "        D   D        ", "        B   B        ", "        B   B        ", "        B   B        ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ", "                     ")
            .where(" ", Predicates.any())
            .where("B", Predicates.blocks(StarTMachineUtils.getKjsBlock("aberration_casing")))
            .where("C", Predicates.blocks(StarTMachineUtils.getKjsBlock("absolute_temperature_smelting_casing"))
                .or(Predicates.abilities(PartAbility.IMPORT_FLUIDS).setMaxGlobalLimited(8).setPreviewCount(0))
                .or(Predicates.abilities(PartAbility.EXPORT_FLUIDS).setMaxGlobalLimited(2).setPreviewCount(0))
                .or(Predicates.abilities(PartAbility.IMPORT_ITEMS).setMaxGlobalLimited(2).setPreviewCount(0))
                .or(Predicates.abilities(PartAbility.EXPORT_ITEMS).setMaxGlobalLimited(2).setPreviewCount(0))
                .or(Predicates.abilities(PartAbility.INPUT_ENERGY).setMaxGlobalLimited(2))
                .or(Predicates.abilities(PartAbility.MAINTENANCE).setExactLimit(1))
                .or(Predicates.abilities(StarTPartAbility.REDSTONE_INTERFACE).setMaxGlobalLimited(4).setPreviewCount(0)))
            .where("D", Predicates.blocks(ChemicalHelper.getBlock(TagPrefix.frameGt, GTCEuAPI.materialManager.getMaterial("gtceu:draco_abyssal"))))
            .where("E", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.of("thermal_extra:dragonsteel_glass", ':'))))
            .where("F", Predicates.blocks(StarTMachineUtils.getKjsBlock("nyanium_engine_intake_casing")))
            .where("G", Predicates.blocks(StarTMachineUtils.getKjsBlock("nyanium_firebox_casing")))
            .where("H", Predicates.blocks(StarTMachineUtils.getKjsBlock("infernally_reinforced_casing")))
            .where("I", Predicates.blocks(GCYMBlocks.HEAT_VENT.get()))
            .where("J", Predicates.blocks(StarTMachineUtils.getKjsBlock("nyanium_pipe_casing")))
            .where("K", Predicates.blocks(StarTMachineUtils.getKjsBlock("nyanium_machine_casing")))
            .where("L", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.of("thermal:enderium_glass", ':'))))
            .where("M", Predicates.blocks(StarTMachineUtils.getKjsBlock("runic_stabilization_casing")))
            .where("N", Predicates.blocks(StarTMachineUtils.getKjsBlock("soul_of_the_flame")))
            .where("@", Predicates.controller(Predicates.blocks(definition.get())))
            .build())
        .workableCasingModel(KubeJS.id("block/casings/riftic_multis/absolute_temperature_smelting_casing"),
            GTCEu.id("block/machines/alloy_smelter"))
        .register();

    public static void init() {
    }
}
